# Generated by Django 3.2 on 2021-04-20 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, help_text='The price amount for the period unit', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Minute'), (2, 'Hour'), (3, 'Day'), (4, 'Month'), (5, 'Year')], default=3)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.currency')),
            ],
        ),
    ]
