# Generated by Django 3.2 on 2021-04-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    def create_currency(apps, schema_editor):
        Currency = apps.get_model('pricing', 'Currency')
        Currency.objects.get_or_create(
            code="USD", defaults={"name": "US Dollar", "symbol": "$"}
        )

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_currency)
    ]
