# Generated by Django 3.2 on 2021-04-20 13:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210420_1358'),
        ('pricing', '0002_auto_20210420_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, help_text='The price amount for the period unit', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'Minute'), (2, 'Hour'), (3, 'Day'), (4, 'Month'), (5, 'Year')], default=3)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.currency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
