# Generated by Django 3.2 on 2021-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20210420_1358'),
    ]

    operations = [
    ]
