# Generated by Django 3.2 on 2021-04-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    def create_categories(apps, schema_editor):
        Category = apps.get_model('pricing', 'Category')
        Currency = apps.get_model('pricing', 'Currency')

        curr, _cr = Currency.objects.get_or_create(
            code="USD", defaults={"name": "US Dollar", "symbol": "$"}
        )

        Category.objects.get_or_create(
            name="Regular", amount=1.5, currency=curr
        )
        Category.objects.get_or_create(
            name="Fiction", amount=3.0, currency=curr
        )
        Category.objects.get_or_create(
            name="Novel", amount=1.5, currency=curr
        )

    dependencies = [
        ('pricing', '0004_auto_20210420_1358'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
