# Generated by Django 3.2 on 2021-04-20 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20210420_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='changed_amount',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='The charge after period limit is hit', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='category',
            name='period_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text='The amount of period units after that the price changes'),
        ),
        migrations.AlterField(
            model_name='category',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='The minimum price amount for the period unit', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
