# Generated by Django 3.2 on 2021-04-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20210420_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
