# Generated by Django 3.2 on 2021-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='bookrent',
            name='price',
        ),
    ]
