# Generated by Django 3.2 on 2021-04-20 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210420_1358'),
        ('pricing', '0003_auto_20210420_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.category'),
        ),
    ]
