# Generated by Django 3.2 on 2021-04-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20210420_1443'),
        ('books', '0003_book_category'),
    ]

    def set_category(apps, schema_editor):
        Category = apps.get_model('pricing', 'Category')
        Currency = apps.get_model('pricing', 'Currency')
        Book = apps.get_model('books', 'Book')

        curr, _cr = Currency.objects.get_or_create(
            code="USD", defaults={"name": "US Dollar", "symbol": "$"}
        )

        default_category, _cr = Category.objects.get_or_create(
            name="Regular", amount=1.5, currency=curr
        )

        Book.objects.filter(category__isnull=True).update(category=default_category)

    operations = [
        migrations.RunPython(set_category),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.category'),
        ),
    ]
